# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "49c7c8e98c61017cfb1597bdb1b359d4"
name = "testing-v7"
handle = "testing-v7"
application_url = "https://volt-cod-your-cards.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://volt-cod-your-cards.trycloudflare.com/auth/callback", "https://volt-cod-your-cards.trycloudflare.com/auth/shopify/callback", "https://volt-cod-your-cards.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
